@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}/posts?page=1
Content-Type: {{contentType}}

###
POST http://{{host}}/posts
Content-Type: {{contentType}}

{
    "key": "keykeykey29",
    "value": "valuevaluevaluevalue1"
}

###
DELETE http://{{host}}/posts
Content-Type: {{contentType}}

{
    "key": "keykeykey27",
    "value": "valuevaluevaluevalue1"
}

