@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json


###
GET http://{{host}}/myip
Content-Type: {{contentType}}

###
GET http://{{host}}/myipcache2
Content-Type: {{contentType}}

###
POST http://{{host}}/findip
Content-Type: {{contentType}}

{
    "ip": "104.28.246.185"
}

###
POST http://{{host}}/findipcache2
Content-Type: {{contentType}}

{
    "ip": "104.28.246.181"
}

